[package]
name = "mauxbot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "*", features = ["full", "rt-multi-thread"]}
serenity = {default-features = false, features = ["full"], version = "*"}
dotenv = "0.15"